### ISSUE TITLE
Missing Container Constraints in 17.0-hibernate-validator-6.2.0-Final version

### ISSUE THREAD

**Issue by arnesenfamily** [graphql-java/graphql-java-extended-validation#59]
**Describe the bug**
The @ContainerSize and @ContainerNotEmpty directives are ignored in the 17.0-hibernate-validator-6.2.0-Final jar in maven central. 

**To Reproduce**
@ContainerNoEmpty and @ContainerSize are ignored when included in a schema when using the 17.0-hibernate-validator-6.2.0-Final jar version. 

If I'm reading things correctly, it looks like the [v17.x-validator-6.2.0.Final](https://github.com/graphql-java/graphql-java-extended-validation/tree/v17.x-validator-6.2.0.Final) branch was the one used to build the 17.0-hibernate-validator-6.2.0-Final jar in maven central and based on a diff of that branch and master, the ContainerSizeConstraint and ContainerNotEmptyConstraint objects are missing. I'm not sure if this was a timing thing or a feasibility thing (e.g. those two constraints don't work with validator 6.2.0-Final), but is there any way we could get a jar published to maven with graphql-java 17.x and hibernate 6.2.0-Final support that includes these two missing contraints?

**Comment by dondonz** [comment]
Hello, sorry for the very delayed reply. This was probably left off unintentionally, given the difficulty in maintaining two parallel versions of the library.

We have since discontinued these special backwards compatible releases, more explanation in this comment: https://github.com/graphql-java/graphql-java-extended-validation/issues/94#issuecomment-1872672422

Sorry we didn't see your issue earlier!
