### ISSUE TITLE
Issue upgrading to GraphQL-java 19.1

### ISSUE THREAD

**Issue by pelletier197** [graphql-java/graphql-java-extended-validation#73]
**Describe the bug**
Directives were changed to `AppliedDirective` in GraphQL 19.1 it seems, which skips validations completely. Switching to `AppliedDirective` today seemed to have no impact at all.  See #72 

**To Reproduce**
Upgrade to java-graphql 19.1, and normally all directives will fail to validate.

**Comment by enriquedacostacambio** [comment]
are you using `graphql-java-tools`? if so, i think the issue may happen due to upgrading that library rather than `graphql-java`.
see: https://github.com/graphql-java/graphql-java-extended-validation/pull/72

Either way, upgrading `graphql-java-extended-validation` to use applied directives instead of old style ones bypasses this issue. +1 on you pr.

**Comment by pelletier197** [comment]
Only missing a release of the library to fix the problem. Although I think it would be important to upgrade the library to use GraphQL version 19 as well.

**Comment by dondonz** [comment]
Closing as #72 has been merged.
